In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns


In [19]:
from sklearn.datasets import make_classification
X, y= make_classification(n_samples= 500, n_features= 4, random_state=200)

In [22]:
data = pd.DataFrame(data = X) 

SyntaxError: positional argument follows keyword argument (<ipython-input-22-9e6fe487eadd>, line 1)

In [23]:
data['target'] = y 

In [24]:
data

0         1         2         3  target
0    1.180984 -0.392328  0.395615  1.490950       1
1    1.038899 -0.353167  0.407637  1.252005       1
2   -0.167539 -0.221197  1.996933 -2.262845       1
3    0.185295 -0.277285  1.661847 -1.364504       1
4   -2.188238  0.636068 -0.059133 -3.435906       1
..        ...       ...       ...       ...     ...
495  0.891653 -0.553922  2.209786 -0.783809       1
496  0.738983 -0.467830  1.896323 -0.714449       1
497  1.394085 -0.647912  1.837344  0.390790       1
498  0.206085  0.023928 -0.616098  0.944735       0
499 -0.253475 -0.086339  1.179789 -1.583643       1

[500 rows x 5 columns]

In [26]:
## Using Newton's Method for logistic regression optimisation


In [36]:
def sigmoid(b0, b1, X):
    return 1/(1+np.exp(-(b0 + b1 *X)))


In [28]:
def log_likelihood(b0, b1, x, y):
    sigmoid_prob = sigmoid(b0, b1, x)
    return np.sum(y*np.log(sigmoid_prob) + (1-y)*np.log(1- sigmoid_prob) )

In [39]:
def jacobian(b0, b1, x, y):
    sigmoid_prob = sigmoid(b0, b1, x) 
    return np.array([[np.sum((y - sigmoid_prob) * x),
                    np.sum(y - sigmoid_prob)]])


def hessian(b0, b1, x, y):
    sigmoid_prob = sigmoid(b0, b1, x)
    a11 = np.sum(sigmoid_prob * (1 - sigmoid_prob) * x * x)
    a12 = np.sum(sigmoid_prob * (1 - sigmoid_prob) * x * 1)
    a22 = np.sum(sigmoid_prob * (1 - sigmoid_prob) * 1 * 1)
    return np.array([[a11, a12],[a12, a22]])


In [47]:
def newtons_method(x, y):
    """
    :input data x(np.array(float))
    :outplut data y(np.array(bool))
    :returns np.array of logreg's parameters after convergence to global maxima for strictly concave function( because of taking log of likelihood)
    """

    #Initialising log_likelihood and parameters b0, b1
    b0 = 0
    b1 = 2
    cost_reduction = np.Infinity
    l = log_likelihood(b0, b1, x, y)

    #Convergence condition
    delta = 0.0000000001
    max_iterations = 15
    
    i = 0

    while abs(cost_reduction) > delta and i < max_iterations:
        i +=1
        g = jacobian(b0, b1, x, y)
        h = hessian(b0, b1,x, y) 
        h_inv = np.linalg.inv(h)

        update = h_inv @ g.T
        update_b0 = update[0][0]
        update_b1 = update[1][0]

        # Perform uodate steps
        b0 += update_b0
        b1 += update_b1

        #update the loglikelihood for each iteration
        l_new = log_likelihood(b0, b1, x, y)
        cost_reduction = l - l_new
        l = l_new

    return np.array([b0, b1])        


In [40]:
x = data[0]
y = data['target']

newtons_method(x, y)

array([ 60973502.87043228, -52670840.50103921])

In [46]:
x = data[0]
y = data['target']

newtons_method(x, y)

array([2.38566146e+11, 2.04219272e+11])

In [48]:
x = data[0]
y = data['target']

newtons_method(x, y)

array([-4.90698418e+25,  4.66373099e+25])

Resources


https://thelaziestprogrammer.com/sharrington/math-of-machine-learning/solving-logreg-newtons-method#:~:text=Logistic%20Regression%20introduces%20the%20concept,transformation%20called%20the%20sigmoid%20function.



https://medium.com/@papillonbee/logistic-regression-from-scratch-with-gradient-descent-and-newtons-method-ff4307e3cb30
